### ISSUE TITLE
Удалить имя компании

### ISSUE THREAD

**Issue by SergerGood** [IAmAnatolyBelanov/InfotecsTestPeriodTask#9]
Если это возможно, то лучше переименовать и не использовать имя компании в имени репозитория и в коде

**Comment by IAmAnatolyBelanov** [comment]
В имени репы ок, а в коде почему нет?  У нас же стайл гайды говорят, что неймспейсы должны начинаться с имени компании вроде

**Comment by SergerGood** [comment]
чтобы не светится в интернете лишний раз без повода)

**Comment by IAmAnatolyBelanov** [comment]
Сделано
